ALTER SESSION SET CONTAINER = PDB1;
WHENEVER SQLERROR EXIT FAILURE;

CREATE MATERIALIZED VIEW TICKLY.prioritate REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.prioritate@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.status REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.status@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.categorie REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.categorie@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.tag REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.tag@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.topic REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.topic@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.departament REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.departament@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.topic_serviciu REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.topic_serviciu@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.topic_produs REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.topic_produs@LINK_SV4;

CREATE TABLE TICKLY.agent_profil (
    agent_id NUMBER PRIMARY KEY,
    nume VARCHAR2(50) NOT NULL,
    prenume VARCHAR2(50) NOT NULL,
    telefon VARCHAR2(20),
    hire_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE TICKLY.client_fizic (
    client_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 2) PRIMARY KEY,
    phone VARCHAR2(20),
    registration_date DATE DEFAULT SYSDATE NOT NULL,
    cnp VARCHAR2(13) NOT NULL UNIQUE,
    nume VARCHAR2(50) NOT NULL,
    prenume VARCHAR2(50) NOT NULL,
    data_nasterii DATE
);

CREATE TABLE TICKLY.ticket_fizic (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 2) PRIMARY KEY,
    client_id NUMBER NOT NULL,
    prioritate_id NUMBER NOT NULL,
    status_id NUMBER NOT NULL,
    categorie_id NUMBER,
    titlu VARCHAR2(200) NOT NULL,
    descriere VARCHAR2(4000),
    data_creare DATE DEFAULT SYSDATE NOT NULL,
    data_rezolvare DATE,
    timp_rezolvare_ore NUMBER,
    CONSTRAINT fk_tf_client FOREIGN KEY (client_id) REFERENCES TICKLY.client_fizic(client_id)
);

CREATE TABLE TICKLY.comment_client_fizic (
    comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 2) PRIMARY KEY,
    ticket_id NUMBER NOT NULL,
    client_id NUMBER NOT NULL,
    content VARCHAR2(4000) NOT NULL,
    created_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_ccf_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_fizic(ticket_id) ON DELETE CASCADE,
    CONSTRAINT fk_ccf_client FOREIGN KEY (client_id) REFERENCES TICKLY.client_fizic(client_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.ticket_tag_fizic (
    ticket_id NUMBER NOT NULL,
    tag_id NUMBER NOT NULL,
    CONSTRAINT pk_ttf PRIMARY KEY (ticket_id, tag_id),
    CONSTRAINT fk_ttf_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_fizic(ticket_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.adresa_fizic (
    adresa_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    client_id NUMBER NOT NULL,
    tip_adresa VARCHAR2(20) CHECK (tip_adresa IN ('FACTURARE', 'LIVRARE', 'SEDIU')),
    strada VARCHAR2(100) NOT NULL,
    numar VARCHAR2(10),
    oras VARCHAR2(50) NOT NULL,
    judet VARCHAR2(50),
    cod_postal VARCHAR2(10),
    tara VARCHAR2(50) DEFAULT 'Romania',
    este_principala CHAR(1) DEFAULT 'N' CHECK (este_principala IN ('Y', 'N')),
    CONSTRAINT fk_adresa_client_f FOREIGN KEY (client_id) REFERENCES TICKLY.client_fizic(client_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.comment_agent_fizic (
    comment_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ticket_id NUMBER NOT NULL,
    agent_id NUMBER NOT NULL,
    content VARCHAR2(4000) NOT NULL,
    created_date DATE DEFAULT SYSDATE NOT NULL,
    is_internal CHAR(1) DEFAULT 'N' CHECK (is_internal IN ('Y', 'N')),
    CONSTRAINT fk_caf_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_fizic(ticket_id) ON DELETE CASCADE,
    CONSTRAINT fk_caf_agent FOREIGN KEY (agent_id) REFERENCES TICKLY.agent_profil(agent_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.ticket_history_fizic (
    history_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ticket_id NUMBER NOT NULL,
    event_type VARCHAR2(50) NOT NULL,
    created_date DATE DEFAULT SYSDATE NOT NULL,
    created_by_role VARCHAR2(10) NOT NULL,
    created_by_id NUMBER NOT NULL,
    author_name VARCHAR2(200),
    display_text VARCHAR2(500),
    CONSTRAINT fk_thf_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_fizic(ticket_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.feedback_fizic (
    feedback_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ticket_id NUMBER NOT NULL UNIQUE,
    rating NUMBER(1) CHECK (rating BETWEEN 1 AND 5),
    comentariu VARCHAR2(1000),
    data_feedback DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_ff_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_fizic(ticket_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.solutie_fizic (
    solutie_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ticket_id NUMBER NOT NULL UNIQUE,
    agent_id NUMBER NOT NULL,
    descriere_solutie VARCHAR2(4000) NOT NULL,
    pasi_rezolvare VARCHAR2(4000),
    data_rezolvare DATE DEFAULT SYSDATE NOT NULL,
    timp_rezolvare_minute NUMBER,
    CONSTRAINT fk_sf_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_fizic(ticket_id) ON DELETE CASCADE,
    CONSTRAINT fk_sf_agent FOREIGN KEY (agent_id) REFERENCES TICKLY.agent_profil(agent_id)
);

CREATE TABLE TICKLY.ticket_agent_fizic (
    ticket_id NUMBER NOT NULL,
    agent_id NUMBER NOT NULL,
    rol VARCHAR2(20) DEFAULT 'PRIMARY' CHECK (rol IN ('PRIMARY', 'SECONDARY', 'OBSERVER')),
    data_asignare DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_taf PRIMARY KEY (ticket_id, agent_id),
    CONSTRAINT fk_taf_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_fizic(ticket_id) ON DELETE CASCADE,
    CONSTRAINT fk_taf_agent FOREIGN KEY (agent_id) REFERENCES TICKLY.agent_profil(agent_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.ticket_topic_fizic (
    ticket_id NUMBER NOT NULL,
    topic_id NUMBER NOT NULL,
    relevanta VARCHAR2(20) DEFAULT 'DIRECT' CHECK (relevanta IN ('DIRECT', 'INDIRECT')),
    CONSTRAINT pk_ttfiz PRIMARY KEY (ticket_id, topic_id),
    CONSTRAINT fk_ttfiz_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_fizic(ticket_id) ON DELETE CASCADE
);

CREATE INDEX TICKLY.idx_cf_nume_upper ON TICKLY.client_fizic(UPPER(nume));
CREATE INDEX TICKLY.idx_tf_client ON TICKLY.ticket_fizic(client_id);
CREATE INDEX TICKLY.idx_tf_status ON TICKLY.ticket_fizic(status_id);

COMMIT;
