ALTER SESSION SET CONTAINER = PDB1;

CREATE OR REPLACE VIEW TICKLY.V_AGENT_GLOBAL AS
SELECT
    P.AGENT_ID,
    P.NUME,
    P.PRENUME,
    P.TELEFON,
    S.EMAIL,
    S.IS_ACTIVE
FROM TICKLY.AGENT_PROFIL P
INNER JOIN TICKLY.AGENT_SEC@LINK_SV3 S
    ON P.AGENT_ID = S.AGENT_ID;

CREATE OR REPLACE FORCE VIEW TICKLY.V_TOATE_TICHETELE AS
SELECT
    TICKET_ID,
    CLIENT_ID,
    'FIZIC' AS TIP,
    TITLU,
    DATA_CREARE
FROM TICKLY.TICKET_FIZIC
UNION ALL
SELECT
    TICKET_ID,
    CLIENT_ID,
    'JURIDIC' AS TIP,
    TITLU,
    DATA_CREARE
FROM TICKLY.TICKET_JURIDIC@LINK_SV2;