ALTER SESSION SET CONTAINER = orclpdb1;

WHENEVER SQLERROR CONTINUE;
BEGIN
  EXECUTE IMMEDIATE 'DROP USER TickLy_DW CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
WHENEVER SQLERROR EXIT FAILURE;

CREATE USER TickLy_DW IDENTIFIED BY "itdev123"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, 
       CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER, CREATE SYNONYM, 
       CREATE MATERIALIZED VIEW, CREATE DATABASE LINK, CREATE ANY DIRECTORY,
       CREATE JOB TO TickLy_DW;

GRANT QUERY REWRITE, GLOBAL QUERY REWRITE TO TickLy_DW;

ALTER USER TickLy_DW QUOTA UNLIMITED ON USERS;

COMMIT;
