ALTER SESSION SET CONTAINER = PDB4;

WHENEVER SQLERROR CONTINUE;
BEGIN
  EXECUTE IMMEDIATE 'DROP USER TICKLY CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
WHENEVER SQLERROR EXIT FAILURE;

CREATE USER TICKLY IDENTIFIED BY "itdev123"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, 
       CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER, CREATE SYNONYM, 
       CREATE MATERIALIZED VIEW, CREATE DATABASE LINK, CREATE ANY DIRECTORY,
       CREATE JOB TO TICKLY;

GRANT QUERY REWRITE, GLOBAL QUERY REWRITE TO TICKLY;

ALTER USER TICKLY QUOTA UNLIMITED ON USERS;

COMMIT;
