ALTER SESSION SET CONTAINER = PDB4;
WHENEVER SQLERROR EXIT FAILURE;

CREATE TABLE TICKLY.prioritate (
    prioritate_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nivel NUMBER(1) NOT NULL UNIQUE CHECK (nivel BETWEEN 1 AND 5),
    nume VARCHAR2(20) NOT NULL UNIQUE,
    descriere VARCHAR2(200),
    timp_raspuns_ore NUMBER
);

CREATE TABLE TICKLY.status (
    status_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(30) NOT NULL UNIQUE,
    descriere VARCHAR2(200),
    este_final CHAR(1) DEFAULT 'N' CHECK (este_final IN ('Y', 'N'))
);

CREATE TABLE TICKLY.categorie (
    categorie_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(100) NOT NULL UNIQUE,
    descriere VARCHAR2(500),
    categorie_parinte_id NUMBER,
    CONSTRAINT fk_categorie_parinte FOREIGN KEY (categorie_parinte_id) REFERENCES TICKLY.categorie(categorie_id)
);

CREATE TABLE TICKLY.tag (
    tag_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(50) NOT NULL UNIQUE,
    culoare VARCHAR2(20),
    descriere VARCHAR2(200)
);

CREATE TABLE TICKLY.topic (
    topic_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(100) NOT NULL,
    descriere VARCHAR2(500),
    topic_type CHAR(1) NOT NULL CHECK (topic_type IN ('S', 'P'))
);

CREATE TABLE TICKLY.kb_article (
    kb_article_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    agent_id NUMBER NOT NULL,
    categorie_id NUMBER,
    titlu VARCHAR2(200) NOT NULL,
    content CLOB NOT NULL,
    keywords VARCHAR2(500),
    vizualizari NUMBER DEFAULT 0,
    rating_mediu NUMBER(3,2),
    data_creare DATE DEFAULT SYSDATE NOT NULL,
    este_public CHAR(1) DEFAULT 'Y' CHECK (este_public IN ('Y', 'N')),
    CONSTRAINT fk_kb_categorie FOREIGN KEY (categorie_id) REFERENCES TICKLY.categorie(categorie_id)
);

CREATE TABLE TICKLY.departament (
    departament_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(100) NOT NULL UNIQUE,
    descriere VARCHAR2(500),
    manager_id NUMBER NOT NULL
);

CREATE TABLE TICKLY.topic_serviciu (
    topic_id NUMBER PRIMARY KEY,
    tip_serviciu VARCHAR2(50) NOT NULL,
    durata_estimata NUMBER,
    tarif NUMBER(10,2),
    CONSTRAINT fk_topic_serviciu FOREIGN KEY (topic_id) REFERENCES TICKLY.topic(topic_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.topic_produs (
    topic_id NUMBER PRIMARY KEY,
    versiune VARCHAR2(20),
    categorie VARCHAR2(50),
    pret NUMBER(10,2),
    stoc NUMBER,
    CONSTRAINT fk_topic_produs FOREIGN KEY (topic_id) REFERENCES TICKLY.topic(topic_id) ON DELETE CASCADE
);

CREATE MATERIALIZED VIEW LOG ON TICKLY.prioritate WITH PRIMARY KEY;
CREATE MATERIALIZED VIEW LOG ON TICKLY.status WITH PRIMARY KEY;
CREATE MATERIALIZED VIEW LOG ON TICKLY.categorie WITH PRIMARY KEY;
CREATE MATERIALIZED VIEW LOG ON TICKLY.tag WITH PRIMARY KEY;
CREATE MATERIALIZED VIEW LOG ON TICKLY.topic WITH PRIMARY KEY;
CREATE MATERIALIZED VIEW LOG ON TICKLY.departament WITH PRIMARY KEY;
CREATE MATERIALIZED VIEW LOG ON TICKLY.topic_serviciu WITH PRIMARY KEY;
CREATE MATERIALIZED VIEW LOG ON TICKLY.topic_produs WITH PRIMARY KEY;

COMMIT;
