ALTER SESSION SET CONTAINER = PDB3;
WHENEVER SQLERROR EXIT FAILURE;

CREATE TABLE TickLy.agent_sec (
    agent_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    is_active CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N'))
);

COMMIT;