ALTER SESSION SET CONTAINER = PDB3;

CREATE OR REPLACE PROCEDURE TICKLY.REFRESH_REPLICATED_DATA AS
BEGIN
DBMS_MVIEW.REFRESH('TICKLY.PRIORITATE', 'F');
DBMS_MVIEW.REFRESH('TICKLY.STATUS', 'F');
DBMS_MVIEW.REFRESH('TICKLY.CATEGORIE', 'F');
DBMS_MVIEW.REFRESH('TICKLY.TAG', 'F');
DBMS_MVIEW.REFRESH('TICKLY.TOPIC', 'F');
END;
/

BEGIN
DBMS_SCHEDULER.CREATE_JOB (
job_name        => 'TICKLY.JOB_REFRESH_REPLICATED_DATA',
job_type        => 'PLSQL_BLOCK',
job_action      => 'BEGIN TICKLY.REFRESH_REPLICATED_DATA; END;',
start_date      => SYSTIMESTAMP,
repeat_interval => 'FREQ=MINUTELY;INTERVAL=1',
enabled         => TRUE
);
END;
/
