ALTER SESSION SET CONTAINER = PDB2;
WHENEVER SQLERROR EXIT FAILURE;

CREATE MATERIALIZED VIEW TICKLY.prioritate REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.prioritate@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.status REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.status@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.categorie REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.categorie@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.tag REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.tag@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.topic REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.topic@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.departament REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.departament@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.topic_serviciu REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.topic_serviciu@LINK_SV4;
CREATE MATERIALIZED VIEW TICKLY.topic_produs REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TICKLY.topic_produs@LINK_SV4;

CREATE TABLE TICKLY.agent_profil (
    agent_id NUMBER PRIMARY KEY,
    nume VARCHAR2(50) NOT NULL,
    prenume VARCHAR2(50) NOT NULL,
    telefon VARCHAR2(20),
    hire_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE TICKLY.client_juridic (
    client_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 2 INCREMENT BY 2) PRIMARY KEY,
    phone VARCHAR2(20),
    registration_date DATE DEFAULT SYSDATE NOT NULL,
    cui VARCHAR2(20) NOT NULL UNIQUE,
    denumire VARCHAR2(200) NOT NULL,
    sediu_social VARCHAR2(200),
    reprezentant_legal VARCHAR2(100)
);

CREATE TABLE TICKLY.ticket_juridic (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 2 INCREMENT BY 2) PRIMARY KEY,
    client_id NUMBER NOT NULL,
    prioritate_id NUMBER NOT NULL,
    status_id NUMBER NOT NULL,
    categorie_id NUMBER,
    titlu VARCHAR2(200) NOT NULL,
    descriere VARCHAR2(4000),
    data_creare DATE DEFAULT SYSDATE NOT NULL,
    data_rezolvare DATE,
    timp_rezolvare_ore NUMBER,
    CONSTRAINT fk_tj_client FOREIGN KEY (client_id) REFERENCES TICKLY.client_juridic(client_id)
);

CREATE TABLE TICKLY.comment_client_juridic (
    comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 2 INCREMENT BY 2) PRIMARY KEY,
    ticket_id NUMBER NOT NULL,
    client_id NUMBER NOT NULL,
    content VARCHAR2(4000) NOT NULL,
    created_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_ccj_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_juridic(ticket_id) ON DELETE CASCADE,
    CONSTRAINT fk_ccj_client FOREIGN KEY (client_id) REFERENCES TICKLY.client_juridic(client_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.ticket_tag_juridic (
    ticket_id NUMBER NOT NULL,
    tag_id NUMBER NOT NULL,
    CONSTRAINT pk_ttj PRIMARY KEY (ticket_id, tag_id),
    CONSTRAINT fk_ttj_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_juridic(ticket_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.adresa_juridic (
    adresa_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    client_id NUMBER NOT NULL,
    tip_adresa VARCHAR2(20) CHECK (tip_adresa IN ('FACTURARE', 'LIVRARE', 'SEDIU')),
    strada VARCHAR2(100) NOT NULL,
    numar VARCHAR2(10),
    oras VARCHAR2(50) NOT NULL,
    judet VARCHAR2(50),
    cod_postal VARCHAR2(10),
    tara VARCHAR2(50) DEFAULT 'Romania',
    este_principala CHAR(1) DEFAULT 'N' CHECK (este_principala IN ('Y', 'N')),
    CONSTRAINT fk_adresa_client_j FOREIGN KEY (client_id) REFERENCES TICKLY.client_juridic(client_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.comment_agent_juridic (
    comment_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ticket_id NUMBER NOT NULL,
    agent_id NUMBER NOT NULL,
    content VARCHAR2(4000) NOT NULL,
    created_date DATE DEFAULT SYSDATE NOT NULL,
    is_internal CHAR(1) DEFAULT 'N' CHECK (is_internal IN ('Y', 'N')),
    CONSTRAINT fk_caj_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_juridic(ticket_id) ON DELETE CASCADE,
    CONSTRAINT fk_caj_agent FOREIGN KEY (agent_id) REFERENCES TICKLY.agent_profil(agent_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.ticket_history_juridic (
    history_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ticket_id NUMBER NOT NULL,
    event_type VARCHAR2(50) NOT NULL,
    created_date DATE DEFAULT SYSDATE NOT NULL,
    created_by_role VARCHAR2(10) NOT NULL,
    created_by_id NUMBER NOT NULL,
    author_name VARCHAR2(200),
    display_text VARCHAR2(500),
    CONSTRAINT fk_thj_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_juridic(ticket_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.feedback_juridic (
    feedback_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ticket_id NUMBER NOT NULL UNIQUE,
    rating NUMBER(1) CHECK (rating BETWEEN 1 AND 5),
    comentariu VARCHAR2(1000),
    data_feedback DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_fj_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_juridic(ticket_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.solutie_juridic (
    solutie_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ticket_id NUMBER NOT NULL UNIQUE,
    agent_id NUMBER NOT NULL,
    descriere_solutie VARCHAR2(4000) NOT NULL,
    pasi_rezolvare VARCHAR2(4000),
    data_rezolvare DATE DEFAULT SYSDATE NOT NULL,
    timp_rezolvare_minute NUMBER,
    CONSTRAINT fk_sj_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_juridic(ticket_id) ON DELETE CASCADE,
    CONSTRAINT fk_sj_agent FOREIGN KEY (agent_id) REFERENCES TICKLY.agent_profil(agent_id)
);

CREATE TABLE TICKLY.ticket_agent_juridic (
    ticket_id NUMBER NOT NULL,
    agent_id NUMBER NOT NULL,
    rol VARCHAR2(20) DEFAULT 'PRIMARY' CHECK (rol IN ('PRIMARY', 'SECONDARY', 'OBSERVER')),
    data_asignare DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_taj PRIMARY KEY (ticket_id, agent_id),
    CONSTRAINT fk_taj_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_juridic(ticket_id) ON DELETE CASCADE,
    CONSTRAINT fk_taj_agent FOREIGN KEY (agent_id) REFERENCES TICKLY.agent_profil(agent_id) ON DELETE CASCADE
);

CREATE TABLE TICKLY.ticket_topic_juridic (
    ticket_id NUMBER NOT NULL,
    topic_id NUMBER NOT NULL,
    relevanta VARCHAR2(20) DEFAULT 'DIRECT' CHECK (relevanta IN ('DIRECT', 'INDIRECT')),
    CONSTRAINT pk_ttjur PRIMARY KEY (ticket_id, topic_id),
    CONSTRAINT fk_ttjur_ticket FOREIGN KEY (ticket_id) REFERENCES TICKLY.ticket_juridic(ticket_id) ON DELETE CASCADE
);

CREATE INDEX TICKLY.idx_cj_denumire_upper ON TICKLY.client_juridic(UPPER(denumire));
CREATE INDEX TICKLY.idx_tj_client ON TICKLY.ticket_juridic(client_id);
CREATE INDEX TICKLY.idx_tj_status ON TICKLY.ticket_juridic(status_id);

COMMIT;
