ALTER SESSION SET CONTAINER = PDB2;
WHENEVER SQLERROR EXIT FAILURE;

CREATE MATERIALIZED VIEW TickLy.prioritate REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TickLy.prioritate@link_sv4;
CREATE MATERIALIZED VIEW TickLy.status REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TickLy.status@link_sv4;
CREATE MATERIALIZED VIEW TickLy.categorie REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TickLy.categorie@link_sv4;
CREATE MATERIALIZED VIEW TickLy.tag REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TickLy.tag@link_sv4;
CREATE MATERIALIZED VIEW TickLy.topic REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM TickLy.topic@link_sv4;

CREATE TABLE TickLy.agent_profil (
    agent_id NUMBER PRIMARY KEY,
    nume VARCHAR2(50) NOT NULL,
    prenume VARCHAR2(50) NOT NULL,
    telefon VARCHAR2(20),
    hire_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE TickLy.client_juridic (
    client_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 2 INCREMENT BY 2) PRIMARY KEY,
    email VARCHAR2(100) NOT NULL UNIQUE,
    phone VARCHAR2(20),
    registration_date DATE DEFAULT SYSDATE NOT NULL,
    cui VARCHAR2(20) NOT NULL UNIQUE,
    denumire VARCHAR2(200) NOT NULL,
    sediu_social VARCHAR2(200),
    reprezentant_legal VARCHAR2(100)
);

CREATE TABLE TickLy.ticket_juridic (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 2 INCREMENT BY 2) PRIMARY KEY,
    client_id NUMBER NOT NULL,
    prioritate_id NUMBER NOT NULL,
    status_id NUMBER NOT NULL,
    categorie_id NUMBER,
    titlu VARCHAR2(200) NOT NULL,
    descriere CLOB,
    data_creare DATE DEFAULT SYSDATE NOT NULL,
    data_rezolvare DATE,
    timp_rezolvare_ore NUMBER,
    CONSTRAINT fk_tj_client FOREIGN KEY (client_id) REFERENCES TickLy.client_juridic(client_id)
);

CREATE TABLE TickLy.comment_client_juridic (
    comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 2 INCREMENT BY 2) PRIMARY KEY,
    ticket_id NUMBER NOT NULL,
    client_id NUMBER NOT NULL,
    content CLOB NOT NULL,
    created_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_ccj_ticket FOREIGN KEY (ticket_id) REFERENCES TickLy.ticket_juridic(ticket_id) ON DELETE CASCADE,
    CONSTRAINT fk_ccj_client FOREIGN KEY (client_id) REFERENCES TickLy.client_juridic(client_id) ON DELETE CASCADE
);

CREATE TABLE TickLy.ticket_tag_juridic (
    ticket_id NUMBER NOT NULL,
    tag_id NUMBER NOT NULL,
    CONSTRAINT pk_ttj PRIMARY KEY (ticket_id, tag_id),
    CONSTRAINT fk_ttj_ticket FOREIGN KEY (ticket_id) REFERENCES TickLy.ticket_juridic(ticket_id) ON DELETE CASCADE
);

CREATE INDEX TickLy.idx_cj_denumire_upper ON TickLy.client_juridic(UPPER(denumire));
CREATE INDEX TickLy.idx_tj_client ON TickLy.ticket_juridic(client_id);
CREATE INDEX TickLy.idx_tj_status ON TickLy.ticket_juridic(status_id);

COMMIT;