ALTER SESSION SET CONTAINER = PDB2;

CREATE OR REPLACE TRIGGER TICKLY.TRG_FK_GLOBAL_STATUS
BEFORE INSERT OR UPDATE ON TICKLY.TICKET_JURIDIC
FOR EACH ROW
DECLARE
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT
    FROM TICKLY.STATUS
    WHERE STATUS_ID =:NEW.STATUS_ID;

    IF V_COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'STATUS ID INVALID!');
    END IF;
END;
/
